language: java

sudo: false
dist: trusty

env: # important! otherwise no JDK-specific envs can be set in matrix:include

addons:
  apt:
    packages:
    - graphviz # required for testing the DOT provider

cache:
  directories:
  - $HOME/.m2

before_cache:
  # do not cache our local archives
  - rm -rf $HOME/.m2/repository/net/automatalib/

branches:
  only:
  - master
  - develop

install: true # skip mvn install, because we essentially run the same command in the script routine

script: mvn install -B -Pcode-analysis,bundles

jobs:
  include:
    - stage: Test
      jdk: openjdk8
    - jdk: oraclejdk8
    - jdk: oraclejdk9
      env: FOO=BAR # test values for now. Future versions may set MAVEN_OPTS="$MAVEN_OPTS -Dmaven.compiler.source=1.9 -Dmaven.compiler.target=1.9"
    - stage: Coverage
      jdk: openjdk8 # use openjdk8 build
      script:
        - mvn install -B -Pcode-coverage
        - mvn coveralls:report
    - stage: Deploy
      jdk: openjdk8 # use openjdk8 build
      script: skip # skip regular build
      deploy:
        # define deployment in deploy phase, which is skipped for pull-requests
        provider: script
        script: mvn --settings build-tools/travis-settings.xml -DskipTests=true deploy
        on:
          branch: develop # only auto deploy snapshots
